version: '3.7'

services:
  web:
    build: .
    command: python server.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/usr/src/app/data
    links:
      - mongo
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/
  mongo:
    image: mongo