version: '3.7'

services:
  web:
    build: .
    command: python server.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/usr/src/app/data
    links:
      - mongo
  mongo:
    image: mongo